version: '3.4'

services:
  courseproject.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: courseproject.database
    environment:
      SA_PASSWORD: "KWkW01UnvsJIvxraxUp2"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - backend
  courseproject.api:
    image: ${DOCKER_REGISTRY-}courseproject
    container_name: courseproject.api
    build:
      context: .
      dockerfile: CourseProject/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - courseproject.database
    networks:
      - backend 


networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local